254: Set up github action for integration tests reports

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -31,3 +31,11 @@ jobs:
         run: ./gradlew check
       - name: Run integration tests
         run: ./gradlew integration
+      - name: Test Report
+        uses: phoenix-actions/test-reporting@v8
+        id: test-report               # Set ID reference for step
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+            name: Integration Tests            # Name of the check run which will be created
+            path: reports/jacoco/test/jacocoTestReport.xml    # Path to test results
+            reporter: java-junit        # Format of test results
